// v2-M2 acceptance (E4V2 design §5.2/§5.3/§5.4 + §5.5 verification split "v2-M2 executed"):
// the e4-openspec-gherkin-v1 converter port byte-cross-tested against the Python original's
// outputs on shared fixtures, the sealed e4-step-table-v1 binder (incl. the Amendment-2 PATCH
// form), the A3 parser fuzz test, and the executed T0 in-sync check (full T0 gold set parses,
// binds, and passes 100% against the T0 gold implementation through the hermetic executor).
//
// Fixture provenance: test/fixtures/e4/v2-converter/*.expected.* were generated by running the
// frozen Python original (hit-sdd-bench-e2/src/hit_sdd_e2/authored_spec/openspec.py,
// openspec-gherkin-v1) over the committed *.md sources on 2026-07-09 — the sibling repo stays a
// reference, never a test-time dependency.
import { afterAll, describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { buildBaselineIr, type E4SchemaIR } from "../src/e4/substrate/ir";
import { createE4Prng } from "../src/e4/substrate/prng";
import {
  E4_CONVERTER_ID,
  openSpecToFeature,
  parseOpenSpecScenarioBlocks
} from "../src/e4/v2/converter";
import { E4_STEP_TABLE, E4_STEP_TABLE_ID, bindScenario, scenarioFloorViolations } from "../src/e4/v2/step-table";
import { allScenarioRefs, deriveSpecOfRecord } from "../src/e4/v2/gold-spec";
import { renderStepText, scenarioBulletLines, type E4V2Scenario, type E4V2Step } from "../src/e4/v2/scenario";
import { buildE4V2WorkspaceFiles, renderCapabilitySpecMarkdown } from "../src/e4/v2/workspace";
import { runE4V2ScenarioSet } from "../src/e4/v2/scenario-executor";
import type { E4ExecutorConfig } from "../src/e4/oracle-executor";
import {
  E4_V2_ASSERTION_STEP_PATTERNS,
  E4_V2_REQUEST_STEP_PATTERNS
} from "../src/e4/v2/step-vocabulary";

const REPO_ROOT = resolve(import.meta.dir, "..");
const FIXTURES = join(REPO_ROOT, "test", "fixtures", "e4", "v2-converter");

const EXEC_CONFIG: E4ExecutorConfig = {
  readiness_timeout_ms: 15_000,
  request_timeout_ms: 3_000,
  readiness_poll_interval_ms: 25
};

const tempRoots: string[] = [];

afterAll(async () => {
  for (const root of tempRoots.splice(0)) {
    await rm(root, { recursive: true, force: true });
  }
});

describe("v2-M2 — e4-openspec-gherkin-v1 byte-cross-test vs the Python original", () => {
  const cases = [
    { source: "t0-widgets.md", feature: "widgets" },
    { source: "t0-categories.md", feature: "categories" },
    { source: "adversarial.md", feature: "mixed" }
  ];

  for (const { source, feature } of cases) {
    test(`parse + .feature output is byte-identical on ${source}`, async () => {
      const text = await Bun.file(join(FIXTURES, source)).text();
      const expectedFeature = await Bun.file(join(FIXTURES, source.replace(".md", ".expected.feature"))).text();
      const expectedParse = JSON.parse(await Bun.file(join(FIXTURES, source.replace(".md", ".expected.json"))).text()) as {
        converter_version: string;
        scenarios: Array<{ title: string; steps: Array<{ keyword: string; text: string }> }>;
      };

      expect(openSpecToFeature(text, feature)).toBe(expectedFeature);
      expect(parseOpenSpecScenarioBlocks(text)).toEqual(expectedParse.scenarios as never);
      expect(expectedParse.converter_version).toBe("openspec-gherkin-v1");
      expect(E4_CONVERTER_ID).toBe("e4-openspec-gherkin-v1");
    });
  }

  test("the T0 fixture sources match the live generator output (fixtures cannot silently rot)", () => {
    const spec = deriveSpecOfRecord(buildBaselineIr(), null);

    for (const capability of spec.capabilities) {
      const fixture = Bun.file(join(FIXTURES, `t0-${capability.name}.md`));
      expect(renderCapabilitySpecMarkdown(capability)).toBe(require("node:fs").readFileSync(join(FIXTURES, `t0-${capability.name}.md`), "utf8"));
      expect(fixture.size).toBeGreaterThan(0);
    }
  });
});

describe("v2-M2 — e4-step-table-v1 (sealed binder)", () => {
  function bindSingle(keyword: string, text: string) {
    return bindScenario({ title: "t", steps: [{ keyword: keyword as never, text }] });
  }

  test("every §5.3 form binds to its typed node (PATCH included)", () => {
    const cases: Array<[string, string, Partial<E4V2Step>]> = [
      ["When", 'I send a GET request to "/widgets"', { kind: "request", method: "GET", path: "/widgets" }],
      ["When", 'I send a DELETE request to "/widgets/w1"', { kind: "request", method: "DELETE" }],
      ["When", 'I send a POST request to "/widgets" with body {"id":"w1"}', { kind: "request_body", method: "POST", body_json: '{"id":"w1"}' }],
      ["When", 'I send a PUT request to "/widgets/w1" with body {"id":"w1"}', { kind: "request_body", method: "PUT" }],
      ["When", 'I send a PATCH request to "/widgets/w1" with body {"id":"w1"}', { kind: "request_body", method: "PATCH" }],
      ["When", 'I remember the response field "id" as "new_id"', { kind: "remember", json_path: "id", name: "new_id" }],
      ["Then", "the response status is 201", { kind: "assert_status", status: 201 }],
      ["Then", 'the response field "error.code" equals "validation_error"', { kind: "assert_field_equals", literal_json: '"validation_error"' }],
      ["Then", 'the response field "id" equals the remembered "new_id"', { kind: "assert_field_equals_remembered", name: "new_id" }],
      ["Then", 'the response body equals {"a":1}', { kind: "assert_body_equals", literal_json: '{"a":1}' }],
      ["Then", 'the response has no field "error"', { kind: "assert_no_field", json_path: "error" }],
      ["Then", "the response list has length 3", { kind: "assert_list_length", length: 3 }],
      ["Then", 'the response field "price" is a number', { kind: "assert_field_type", json_type: "number" }]
    ];

    for (const [keyword, text, expected] of cases) {
      const result = bindSingle(keyword, text);
      expect(result.ok).toBe(true);
      if (result.ok) {
        expect(result.scenario.steps[0]).toMatchObject(expected);
      }
    }
  });

  test("violations: unmatched text, unparseable JSON, status classes, negations, contains-forms", () => {
    const violating: Array<[string, string]> = [
      ["When", 'I send a HEAD request to "/widgets"'],
      ["When", 'I send a POST request to "/widgets" with body {not json}'],
      ["Then", "the response status is 2xx"],
      ["Then", "the response status is not 500"],
      ["Then", 'the response field "name" contains "anvil"'],
      ["Then", 'the response field "name" equals the remembered "has space"'],
      ["Then", "the response body equals"],
      ["Given", "a seeded store"]
    ];

    for (const [keyword, text] of violating) {
      const result = bindSingle(keyword, text);
      expect(result.ok).toBe(false);
      if (!result.ok) {
        expect(result.violations[0].step_text).toBe(text);
        expect(result.violations[0].reason.length).toBeGreaterThan(0);
      }
    }
  });

  test("keyword-class binding: assertions under WHEN and requests under THEN are violations; AND binds to the preceding class", () => {
    const wrongClass = bindScenario({
      title: "t",
      steps: [
        { keyword: "When", text: "the response status is 200" },
        { keyword: "Then", text: 'I send a GET request to "/widgets"' }
      ]
    });
    expect(wrongClass.ok).toBe(false);
    if (!wrongClass.ok) {
      expect(wrongClass.violations).toHaveLength(2);
    }

    const andChain = bindScenario({
      title: "t",
      steps: [
        { keyword: "When", text: 'I send a GET request to "/widgets"' },
        { keyword: "And", text: 'I remember the response field "id" as "x"' },
        { keyword: "Then", text: "the response status is 200" },
        { keyword: "And", text: "the response list has length 2" },
        { keyword: "But", text: 'the response has no field "error"' }
      ]
    });
    expect(andChain.ok).toBe(true);

    const danglingAnd = bindScenario({
      title: "t",
      steps: [{ keyword: "And", text: "the response status is 200" }]
    });
    expect(danglingAnd.ok).toBe(false);
  });

  test("the sealed table is the code twin of the README vocabulary: every display pattern instantiates to a binding step", () => {
    expect(E4_STEP_TABLE_ID).toBe("e4-step-table-v1");

    // Instantiate each display pattern's typed placeholders with concrete sample values; every
    // instance must bind under its class, so the README can never advertise a form the table
    // rejects (or vice versa — the table's pattern count is pinned by the binding cases above).
    const instantiate = (pattern: string) =>
      pattern
        .replace("<path>", "/widgets")
        .replace("<json.path>", "error.code")
        .replace("<json-literal>", '{"a":1}')
        .replace("<json>", '{"id":"w1"}')
        .replace("<name>", "saved_value")
        .replace("<int>", "7")
        .replace("<string|number|boolean|array|object>", "string");

    for (const pattern of E4_V2_REQUEST_STEP_PATTERNS) {
      const result = bindScenario({ title: "twin", steps: [{ keyword: "When", text: instantiate(pattern) }] });
      expect(result.ok).toBe(true);
    }

    for (const pattern of E4_V2_ASSERTION_STEP_PATTERNS) {
      const result = bindScenario({ title: "twin", steps: [{ keyword: "Then", text: instantiate(pattern) }] });
      expect(result.ok).toBe(true);
    }

    expect(E4_STEP_TABLE).toHaveLength(10);
  });

  test("floors: a bound scenario with no value-binding assertion or no THEN is flagged", () => {
    const statusOnly: E4V2Scenario = {
      title: "weak",
      steps: [
        { kind: "request", method: "GET", path: "/widgets" },
        { kind: "assert_status", status: 200 }
      ]
    };
    expect(scenarioFloorViolations(statusOnly)).toEqual(["scenario has no value-binding assertion"]);

    const noThen: E4V2Scenario = { title: "no-then", steps: [{ kind: "request", method: "GET", path: "/widgets" }] };
    expect(scenarioFloorViolations(noThen)).toContain("scenario has no THEN assertion");

    const noRequest: E4V2Scenario = { title: "no-request", steps: [{ kind: "assert_status", status: 200 }] };
    expect(scenarioFloorViolations(noRequest)).toContain("scenario sends no request");
  });
});

describe("v2-M2 — parser fuzz (A3)", () => {
  test("the binder never throws and always classifies, over seeded random and mutated-valid step texts", () => {
    const prng = createE4Prng(20260709);
    const alphabet = ' abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"{}[]:,.<>/\\-_*%$#@!()';
    const validTexts = [
      'I send a GET request to "/widgets"',
      'I send a PATCH request to "/widgets/w1" with body {"id":"w1"}',
      "the response status is 200",
      'the response field "error.code" equals "validation_error"',
      "the response list has length 2"
    ];
    const keywords = ["Given", "When", "Then", "And", "But"] as const;

    const randomString = (length: number) =>
      Array.from({ length }, () => alphabet[prng.nextInt(alphabet.length)]).join("");

    for (let i = 0; i < 2_000; i += 1) {
      const roll = prng.nextInt(3);
      let text: string;

      if (roll === 0) {
        text = randomString(1 + prng.nextInt(80));
      } else if (roll === 1) {
        // Mutate a valid step: insert/delete/replace one character.
        const base = validTexts[prng.nextInt(validTexts.length)];
        const position = prng.nextInt(base.length);
        const mutation = prng.nextInt(3);
        text =
          mutation === 0
            ? base.slice(0, position) + alphabet[prng.nextInt(alphabet.length)] + base.slice(position)
            : mutation === 1
              ? base.slice(0, position) + base.slice(position + 1)
              : base.slice(0, position) + alphabet[prng.nextInt(alphabet.length)] + base.slice(position + 1);
      } else {
        text = validTexts[prng.nextInt(validTexts.length)];
      }

      const keyword = keywords[prng.nextInt(keywords.length)];
      const result = bindScenario({ title: "fuzz", steps: [{ keyword, text }] });

      expect(typeof result.ok).toBe("boolean");
      if (!result.ok) {
        expect(result.violations.length).toBeGreaterThanOrEqual(1);
      }
    }
  });

  test("round-trip property: every typed step renders to text that binds back to the identical node", () => {
    const spec = deriveSpecOfRecord(buildBaselineIr(), null);

    for (const ref of allScenarioRefs(spec)) {
      for (const [index, step] of ref.scenario.steps.entries()) {
        const isRequest = step.kind === "request" || step.kind === "request_body" || step.kind === "remember";
        const result = bindScenario({
          title: ref.scenario.title,
          steps: [{ keyword: isRequest ? "When" : "Then", text: renderStepText(step) }]
        });

        if (!result.ok) {
          throw new Error(`step ${index} of "${ref.scenario.title}" failed to re-bind: ${JSON.stringify(result.violations)}`);
        }

        expect(result.scenario.steps[0]).toEqual(step);
      }
    }
  });

  test("the converter never throws on random documents", () => {
    const prng = createE4Prng(97);
    const lineShapes = [
      "#### Scenario: ",
      "### Requirement: ",
      "- **WHEN** ",
      "- **THEN** ",
      "* **AND**: ",
      "",
      "prose "
    ];

    for (let i = 0; i < 300; i += 1) {
      const lines = Array.from({ length: prng.nextInt(30) }, () => {
        const shape = lineShapes[prng.nextInt(lineShapes.length)];
        return `${shape}${"x".repeat(prng.nextInt(20))}`;
      });
      const text = lines.join("\n");
      const scenarios = parseOpenSpecScenarioBlocks(text);

      expect(Array.isArray(scenarios)).toBe(true);
      expect(typeof openSpecToFeature(text, "fuzz")).toBe("string");
    }
  });
});

describe("v2-M2 — executed T0 in-sync check (§5.5)", () => {
  test("the full T0 gold set parses, binds, satisfies floors, and passes 100% against the T0 gold implementation", async () => {
    const ir: E4SchemaIR = buildBaselineIr();
    const files = buildE4V2WorkspaceFiles(ir);
    const dir = await mkdtemp(join(tmpdir(), "e4-v2-insync-"));
    tempRoots.push(dir);

    for (const [path, contents] of Object.entries(files)) {
      await mkdir(dirname(join(dir, path)), { recursive: true });
      await writeFile(join(dir, path), contents);
    }

    // Parse the workspace's own markdown (the agent-visible artifact) — NOT the in-memory model.
    const boundScenarios: E4V2Scenario[] = [];

    for (const capability of ["categories", "widgets"]) {
      const markdown = await Bun.file(join(dir, "openspec", "specs", capability, "spec.md")).text();
      const parsed = parseOpenSpecScenarioBlocks(markdown);

      expect(parsed.length).toBeGreaterThan(0);

      for (const scenario of parsed) {
        const bound = bindScenario(scenario);

        if (!bound.ok) {
          throw new Error(`T0 scenario failed to bind: ${JSON.stringify(bound.violations)}`);
        }

        expect(scenarioFloorViolations(bound.scenario)).toEqual([]);
        boundScenarios.push(bound.scenario);
      }
    }

    // The text→AST pipeline reconstructs exactly the sealed template model (round-trip).
    const model = allScenarioRefs(deriveSpecOfRecord(ir, null)).map((ref) => ref.scenario);
    expect(boundScenarios).toEqual(model);

    // …and the full set passes 100% against the T0 gold implementation, hermetically.
    const verdicts = await runE4V2ScenarioSet({
      workspace_dir: dir,
      scenarios: boundScenarios,
      config: EXEC_CONFIG,
      concurrency: 6
    });
    const notGreen = verdicts
      .filter((verdict) => verdict.kind !== "completed" || !verdict.passed)
      .map((verdict) => verdict.title);

    expect(boundScenarios).toHaveLength(17);
    expect(notGreen).toEqual([]);
  }, 120_000);

  test("the emitted .feature byproduct matches the converter output for the emitted markdown", () => {
    const files = buildE4V2WorkspaceFiles(buildBaselineIr());

    for (const capability of ["categories", "widgets"]) {
      expect(files[`openspec/specs/${capability}/spec.feature`]).toBe(
        openSpecToFeature(files[`openspec/specs/${capability}/spec.md`], capability)
      );
      expect(files[`openspec/specs/${capability}/spec.feature`]).toStartWith(`Feature: ${capability}`);
    }
  });
});
