import { describe, expect, test } from "bun:test";

describe("operator note", () => {
  test("documents the fake-pilot workflow and artifact map", async () => {
    const note = await Bun.file("docs/fake-pilot-operator-note.md").text();

    expect(note).toContain("bun run pilot:fake");
    expect(note).toContain("tasks/role-permissions-calibration");
    expect(note).toContain("tasks/subscription-entitlements-lifecycle");
    expect(note).toContain("bun run pilot:run");
    expect(note).toContain("--agent openrouter");
    expect(note).toContain("--agent openrouter-loop");
    expect(note).toContain("--max-model-turns");
    expect(note).toContain("--max-feedback-runs");
    expect(note).toContain("--request-timeout-ms");
    expect(note).toContain("--max-output-tokens");
    expect(note).toContain("--temperature");
    expect(note).toContain("provider execution profile");
    expect(note).toContain("clean primary evidence eligible");
    expect(note).toContain("model_turn -> feedback_run -> model_turn");
    expect(note).toContain("deepseek/deepseek-v4-flash");
    expect(note).toContain("test/model-loop-agent.test.ts");
    expect(note).toContain("bun run inspect:run");
    expect(note).toContain("bun run pilot:fake --help");
    expect(note).toContain("valid=false");
    expect(note).toContain("runs/<run_id>/run.json");
    expect(note).toContain("summary.md");
    expect(note).toContain("context_only_spec");
    expect(note).toContain("feedback_capable_spec");
    expect(note).toContain("local-acceptance-criteria.json");
    expect(note).toContain("analysis-plan.json");
  });

  test("provides a machine-readable fake-pilot readiness checklist", async () => {
    const checklist = JSON.parse(await Bun.file("docs/fake-pilot-readiness-checklist.json").text());

    expect(checklist.checklist_id).toBe("fake-pilot-readiness-v0");
    expect(checklist.conditions).toEqual(["context_only_spec", "feedback_capable_spec"]);
    expect(checklist.required_commands).toContain("bun test");
    expect(checklist.required_commands).toContain("bun run pilot:run");
    expect(checklist.required_commands).toContain("bun run pilot:fake");
    expect(checklist.required_commands).toContain("bun run inspect:run");
    expect(checklist.required_artifacts).toContain("runs/<run_id>/run.json");
    expect(checklist.required_artifacts).toContain("runs/<run_id>/summary.md");
    expect(checklist.required_artifacts).toContain("runs/<run_id>/<condition>/checkpoints/<checkpoint_id>/hidden-oracle-result.json");
    expect(checklist.gates).toContain("visible_spec_text_equal_across_conditions");
    expect(checklist.gates).toContain("feedback_assets_only_for_feedback_capable_spec");
    expect(checklist.gates).toContain("cli_help_available");
    expect(checklist.gates).toContain("inspect_invalid_run_nonzero");
    expect(checklist.gates).toContain("task_package_unique_ids");
    expect(checklist.gates).toContain("run_manifest_checkpoint_sequence_matches_top_level");
    expect(checklist.gates).toContain("result_schema_unique_check_ids");
    expect(checklist.gates).toContain("result_schema_check_fields_valid");
    expect(checklist.gates).toContain("agent_status_matches_manifest");
    expect(checklist.gates).toContain("agent_result_notes_field_valid");
    expect(checklist.gates).toContain("run_manifest_unique_checkpoint_entries");
    expect(checklist.gates).toContain("replay_checkpoint_hashes_match_run_manifest");
    expect(checklist.gates).toContain("replay_agent_status_matches_run_manifest");
    expect(checklist.gates).toContain("result_schema_evaluation_fields_valid");
    expect(checklist.gates).toContain("result_schema_checkpoint_regression_free_success");
    expect(checklist.gates).toContain("result_schema_regression_free_auc");
    expect(checklist.gates).toContain("agent_result_schema_valid");
    expect(checklist.gates).toContain("openrouter_agent_adapter_available");
    expect(checklist.gates).toContain("openrouter_agent_mock_tested");
    expect(checklist.gates).toContain("openrouter_api_key_required");
    expect(checklist.gates).toContain("direct_openrouter_chosen_before_opencode_bridge");
    expect(checklist.gates).toContain("openrouter_loop_agent_adapter_available");
    expect(checklist.gates).toContain("openrouter_loop_mock_tested");
    expect(checklist.gates).toContain("model_loop_feedback_gated_by_condition");
    expect(checklist.gates).toContain("model_loop_bounded_turn_policy");
    expect(checklist.gates).toContain("context_only_self_review_without_feedback_output");
    expect(checklist.gates).toContain("feedback_summary_public_safe");
    expect(checklist.gates).toContain("feedback_asset_immutability_enforced");
    expect(checklist.gates).toContain("model_loop_agent_result_provenance");
    expect(checklist.gates).toContain("causal_feedback_use_evidence_enforced");
    expect(checklist.gates).toContain("causal_feedback_opportunity_transcript_sequence_enforced");
    expect(checklist.gates).toContain("provider_network_validity_details_recorded");
    expect(checklist.gates).toContain("provider_execution_profile_recorded");
    expect(checklist.gates).toContain("provider_execution_profile_compatibility_checked");
    expect(checklist.gates).toContain("clean_primary_evidence_eligibility_recorded");
    expect(checklist.gates).toContain("provider_timeout_failure_phase_classified");
    expect(checklist.gates).toContain("provider_failure_workspace_carry_forward_recorded");
    expect(checklist.gates).toContain("checkpoint_provider_failure_carry_forward_verified");
    expect(checklist.gates).toContain("workspace_snapshot_records_match_manifest");
    expect(checklist.gates).toContain("workspace_snapshot_declared_paths_verified");
    expect(checklist.gates).toContain("checkpoint_manifest_agent_status_and_snapshot_paths");
    expect(checklist.gates).toContain("checkpoint_manifest_snapshot_paths_under_artifact_dir");
    expect(checklist.gates).toContain("checkpoint_manifest_snapshot_paths_distinct");
    expect(checklist.gates).toContain("hidden_oracle_check_fields_valid");
    expect(checklist.gates).toContain("hidden_oracle_check_details_valid");
    expect(checklist.gates).toContain("hidden_oracle_result_metadata_valid");
    expect(checklist.gates).toContain("hidden_oracle_checks_non_empty");
    expect(checklist.gates).toContain("hidden_oracle_status_matches_failed_checks");
    expect(checklist.gates).toContain("checkpoint_manifest_hidden_oracle_result_path_declared");
    expect(checklist.gates).toContain("checkpoint_manifest_hidden_oracle_result_path_hash_symmetry");
    expect(checklist.gates).toContain("checkpoint_manifest_hidden_oracle_result_path_under_artifact_dir");
    expect(checklist.gates).toContain("hidden_oracle_declared_path_verified");
    expect(checklist.gates).toContain("result_and_summary_declared_together");
    expect(checklist.gates).toContain("run_manifest_result_summary_field_shapes_valid");
    expect(checklist.gates).toContain("checkpoint_manifest_schema_errors_clean");
    expect(checklist.gates).toContain("workspace_snapshot_drift_fixture");
    expect(checklist.gates).toContain("invalid_checkpoint_manifest_schema_error_fixture");
    expect(checklist.gates).toContain("checkpoint_manifest_path_containment_fixture");
    expect(checklist.gates).toContain("one_sided_result_summary_declaration_fixture");
    expect(checklist.gates).toContain("missing_declared_hidden_oracle_result_fixture");
    expect(checklist.gates).toContain("hidden_oracle_failed_status_mismatch_fixture");
    expect(checklist.gates).toContain("replay_checkpoint_hash_drift_fixture");
    expect(checklist.gates).toContain("replay_agent_status_drift_fixture");
    expect(checklist.gates).toContain("role_permissions_calibration_task_available");
    expect(checklist.gates).toContain("role_permissions_feedback_accumulates_through_i07");
    expect(checklist.gates).toContain("role_permissions_hidden_oracle_isolated");
    expect(checklist.gates).toContain("role_permissions_oracle_reference_passes");
    expect(checklist.gates).toContain("role_permissions_oracle_regression_cases_fail");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_spec_draft_available");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_coverage_manifest_available");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_fake_agent_validation_plan_available");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_local_acceptance_criteria_available");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_analysis_plan_sealed");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_analysis_plan_equal_budget_precommitted");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_analysis_plan_pooling_rules_precommitted");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_visible_feedback_assets_executable");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_hidden_oracle_executable");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_reference_candidate_passes_hidden_oracle");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_targeted_regressions_fail_hidden_oracle");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_no_provider_fake_pilot_validates");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_replay_provenance_compatibility_checked");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_fake_pilot_writes_result_and_summary");
    expect(checklist.gates).toContain("subscription_entitlements_lifecycle_v0_provider_run_requires_explicit_request");
  });

  test("keeps a compact progress log for protocol decisions", async () => {
    const progress = await Bun.file("docs/progress-log.md").text();

    expect(progress).toContain("# Progress Log");
    expect(progress).toContain("two-condition protocol");
    expect(progress).toContain("sample-cart");
    expect(progress).toContain("result-schema-v1");
    expect(progress).toContain("inspect:run");
    expect(progress).toContain("duplicate task-package ID");
    expect(progress).toContain("agent-result status");
    expect(progress).toContain("result check field-shape");
    expect(progress).toContain("evaluation field-shape");
    expect(progress).toContain("workspace snapshot record");
    expect(progress).toContain("checkpoint manifest agent status");
    expect(progress).toContain("hidden-oracle check field");
    expect(progress).toContain("hidden-oracle result metadata");
    expect(progress).toContain("result and summary declarations");
    expect(progress).toContain("invalid checkpoint manifest schema-error fixture");
    expect(progress).toContain("result and summary path/hash field shapes");
    expect(progress).toContain("non-empty checks arrays");
    expect(progress).toContain("failing check requires failed status");
    expect(progress).toContain("one-sided result/summary declaration fixture");
    expect(progress).toContain("checkpoint manifest hashes");
    expect(progress).toContain("agent-result notes field");
    expect(progress).toContain("hidden-oracle check details field");
    expect(progress).toContain("hidden-oracle failed-status mismatch fixture");
    expect(progress).toContain("checkpoint manifest `agent_status`");
    expect(progress).toContain("path/hash declaration symmetry");
    expect(progress).toContain("declared hidden-oracle result paths");
    expect(progress).toContain("replay checkpoint hash drift fixture");
    expect(progress).toContain("declared snapshot paths stay under");
    expect(progress).toContain("hidden-oracle result paths stay under");
    expect(progress).toContain("declared workspace snapshot paths");
    expect(progress).toContain("replay agent-status drift fixture");
    expect(progress).toContain("condition checkpoint sequence");
    expect(progress).toContain("snapshot before/after paths are distinct");
    expect(progress).toContain("path-containment schema-error fixture");
    expect(progress).toContain("missing declared hidden-oracle result paths");
    expect(progress).toContain("direct OpenRouter agent adapter");
    expect(progress).toContain("deepseek/deepseek-v4-flash");
    expect(progress).toContain("--agent openrouter");
    expect(progress).toContain("model-loop adapter");
    expect(progress).toContain("--agent openrouter-loop");
    expect(progress).toContain("feedback summary isolation");
    expect(progress).toContain("feedback asset immutability");
    expect(progress).toContain("opencode CLI bridge");
    expect(progress).toContain("role-permissions-calibration");
    expect(progress).toContain("regression_free_success");
    expect(progress).toContain("regression_free_auc");
    expect(progress).toContain("runs/**");
    expect(progress).toContain("optional Python analysis utility");
    expect(progress).toContain("Deferred charts");
    expect(progress).toContain("../hit-sdd-bench.old");
    expect(progress).toContain("schema-error reporting");
    expect(progress).toContain("no-provider fake-pilot validation coverage");
    expect(progress).toContain("18 replay steps");
    expect(progress).toContain("zero artifact mismatches");
    expect(progress).toContain("local-acceptance-criteria.json");
    expect(progress).toContain("analysis-plan.json");
    expect(progress).toContain("equal 2/1 loop budget");
    expect(progress).toContain("reference template implementation");
    expect(progress).toContain("nine visible feedback assets");
    expect(progress).toContain("executable subscription hidden oracle");
    expect(progress).toContain("targeted regressions fail");
    expect(progress).toContain("provider execution profiles");
    expect(progress).toContain("clean_primary_evidence_eligible");
    expect(progress).toContain("provider timeout phase classification");
    expect(progress).toContain("workspace_carried_forward_due_to_provider_failure");
    expect(progress).toContain("model_turn -> feedback_run -> model_turn");
  });
});
