// `e4-openspec-gherkin-v1` (E4V2 design §5.2 step 1): the TS port of the proven live E2
// converter `openspec-gherkin-v1` (hit-sdd-bench-e2/src/hit_sdd_e2/authored_spec/openspec.py,
// read-only reference). OpenSpec scenarios are "almost-Gherkin": `#### Scenario:` headers with
// bolded `- **WHEN**` / `- **THEN**` / `- **AND**` bullets; this module parses them and derives
// a real `.feature` rendering (bare keywords) as a deterministic byproduct — never
// hand-maintained, never parsed back.
//
// Byte-fidelity discipline: the parse rules are a LINE-FOR-LINE port of the Python original and
// are byte-cross-tested against outputs generated by that original on shared fixtures
// (test/fixtures/e4/v2-converter/*). Any change to the parse/render rules bumps the converter
// id — the id is sealed in the v2 constants lineage and stamped in every manifest (§5.4).
export const E4_CONVERTER_ID = "e4-openspec-gherkin-v1";

// Ports of _SCENARIO_RE / _STEP_RE / _KEYWORD from the Python original, verbatim semantics:
// 3-or-4-hash scenario headers; `-` or `*` bullets; bolded keyword with optional colon;
// case-insensitive keywords normalized to Gherkin casing; surrounding whitespace trimmed.
const SCENARIO_PATTERN = /^#{3,4}\s+Scenario:\s+(.+?)\s*$/;
const STEP_PATTERN = /^\s*[-*]\s+\*\*(GIVEN|WHEN|THEN|AND|BUT)\*\*\s*:?\s+(.+?)\s*$/i;
const GHERKIN_KEYWORD_CASING: Record<string, string> = {
  given: "Given",
  when: "When",
  then: "Then",
  and: "And",
  but: "But"
};

export type E4ParsedStep = {
  keyword: "Given" | "When" | "Then" | "And" | "But";
  text: string;
};

export type E4ParsedScenario = {
  title: string;
  steps: E4ParsedStep[];
};

// Extract `#### Scenario:` blocks and their bolded keyword bullets from an OpenSpec document.
// Steps before the first scenario header are ignored, exactly as in the original.
export function parseOpenSpecScenarioBlocks(openspecText: string): E4ParsedScenario[] {
  const scenarios: E4ParsedScenario[] = [];
  let title: string | null = null;
  let steps: E4ParsedStep[] = [];

  const flush = (): void => {
    if (title !== null) {
      scenarios.push({ title, steps });
    }
    title = null;
    steps = [];
  };

  for (const line of openspecText.split(/\r\n|\r|\n/)) {
    const header = line.match(SCENARIO_PATTERN);

    if (header) {
      flush();
      title = header[1].trim();
      continue;
    }

    const step = line.match(STEP_PATTERN);

    if (step && title !== null) {
      steps.push({
        keyword: GHERKIN_KEYWORD_CASING[step[1].toLowerCase()] as E4ParsedStep["keyword"],
        text: step[2].trim()
      });
    }
  }

  flush();
  return scenarios;
}

// Convert an OpenSpec document's scenarios into a valid Gherkin `.feature` (bare keywords) —
// the derived byproduct emitted into the workspace (§5.2 step 1).
export function openSpecToFeature(openspecText: string, feature: string): string {
  const lines = [`Feature: ${feature}`];

  for (const scenario of parseOpenSpecScenarioBlocks(openspecText)) {
    lines.push("", `  Scenario: ${scenario.title}`);

    for (const step of scenario.steps) {
      lines.push(`    ${step.keyword} ${step.text}`);
    }
  }

  return `${lines.join("\n").replace(/\s+$/, "")}\n`;
}
