// v2 app codegen (E4V2 design §5.6 `procedural-rest-v2`, Amendment 2). Same generated-app shape
// as v1 (src/e4/substrate/scaffold.ts, untouched): one generic server driven by generated data
// files. The registry/schema/seed DUMP FORMAT is byte-compatible with v1 (the §7.5 code-side
// meter channel reads it unchanged); the server behavior is stricter per §5.6.1:
//
//   Full request validation on create and update bodies, sealed check order —
//     unknown field → missing required → type → validation rule; first failure wins;
//     status 400, machine code "validation_error", envelope per the error_format convention.
//   Type checks: string/ref = JSON string (no referential-integrity check — recorded
//     limitation), int = integer number, decimal = finite number (integers admissible),
//     bool = boolean, date = string matching ^\d{4}-\d{2}-\d{2}$; null is treated as absent.
//   Enforced rules: range (min/max), enum (membership), format (pattern).
//
// v2 emits NO specs/openapi.json and NO specs/CONVENTIONS.md (§5.5 workspace shape: the OpenSpec
// tree is THE agent-facing spec; that tree plus the README are emitted by the v2-M1 workspace
// generator, not here). This module owns only the runnable app files.
import { generateSeedFixtureV2 } from "./testgen";
import type { E4SchemaIR } from "../ir";
import {
  ERROR_FORMAT_STATEMENT_CODE_MESSAGE,
  ERROR_FORMAT_STATEMENT_TYPE_DETAIL
} from "./ops";

const ERROR_FORMAT_STYLE_BY_STATEMENT: Record<string, "code_message" | "type_detail"> = {
  [ERROR_FORMAT_STATEMENT_CODE_MESSAGE]: "code_message",
  [ERROR_FORMAT_STATEMENT_TYPE_DETAIL]: "type_detail"
};

export function errorEnvelopeStyleV2(ir: E4SchemaIR): "code_message" | "type_detail" {
  const convention = ir.conventions.find((candidate) => candidate.kind === "error_format");
  const style = convention ? ERROR_FORMAT_STYLE_BY_STATEMENT[convention.statement] : undefined;

  if (!style) {
    throw new Error(`unrecognized error_format convention statement: ${convention?.statement}`);
  }

  return style;
}

// The two envelope key pairs, resolved exactly as the server resolves them (§5.5's ⟨k1⟩/⟨k2⟩).
export function errorEnvelopeKeysV2(ir: E4SchemaIR): [string, string] {
  return errorEnvelopeStyleV2(ir) === "type_detail" ? ["type", "detail"] : ["code", "message"];
}

// Statement-level resolution for consumers that hold a convention statement rather than a full
// IR (the §7.5 spec-side convention-coverage rule resolves keys exactly this way).
export function envelopeKeysForStatement(statement: string): [string, string] | null {
  const style = ERROR_FORMAT_STYLE_BY_STATEMENT[statement];
  return style === undefined ? null : style === "type_detail" ? ["type", "detail"] : ["code", "message"];
}

function registryFileContents(ir: E4SchemaIR): string {
  const routes = ir.endpoints.map((endpoint) => ({
    method: endpoint.method,
    path: endpoint.path,
    entity: endpoint.entity,
    kind: endpoint.kind
  }));

  return [
    "// GENERATED by src/e4/substrate/v2/scaffold.ts — do not hand-edit route wiring here.",
    'export type E4RouteDefinition = {',
    '  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";',
    "  path: string;",
    "  entity: string;",
    '  kind: "create" | "read" | "update" | "delete" | "list" | "analytics";',
    "};",
    "",
    `export const routeRegistry: E4RouteDefinition[] = ${JSON.stringify(routes, null, 2)};`,
    ""
  ].join("\n");
}

function schemaFileContents(ir: E4SchemaIR): string {
  const entitySchemas = ir.entities.map((entity) => ({
    name: entity.name,
    fields: entity.fields.map((field) => ({
      name: field.name,
      type: field.type,
      ref_entity: field.ref_entity ?? null,
      required: field.required
    }))
  }));
  const validationRules = ir.validation_rules.map((rule) => ({
    entity: rule.entity,
    field: rule.field,
    kind: rule.kind,
    detail: rule.detail
  }));

  return [
    "// GENERATED by src/e4/substrate/v2/scaffold.ts — the app's actual behavior tracks this file.",
    'export type E4FieldType = "string" | "int" | "decimal" | "bool" | "date" | "ref";',
    "export type E4FieldSchema = { name: string; type: E4FieldType; ref_entity: string | null; required: boolean };",
    "export type E4EntitySchema = { name: string; fields: E4FieldSchema[] };",
    'export type E4ValidationRuleSchema = { entity: string; field: string; kind: "required" | "range" | "enum" | "format"; detail: Record<string, unknown> };',
    "",
    `export const entitySchemas: E4EntitySchema[] = ${JSON.stringify(entitySchemas, null, 2)};`,
    "",
    `export const validationRules: E4ValidationRuleSchema[] = ${JSON.stringify(validationRules, null, 2)};`,
    "",
    `export const errorEnvelopeStyle: "code_message" | "type_detail" = ${JSON.stringify(errorEnvelopeStyleV2(ir))};`,
    ""
  ].join("\n");
}

function seedFileContents(ir: E4SchemaIR): string {
  const fixture = generateSeedFixtureV2(ir);

  return [
    "// GENERATED by src/e4/substrate/v2/scaffold.ts.",
    "export const seedFixture: Record<string, Record<string, unknown>[]> = " + JSON.stringify(fixture, null, 2) + ";",
    ""
  ].join("\n");
}

const STORAGE_FILE_CONTENTS = `// In-memory store (ADR-002): the server process is the unit of state. Every executor run is
// fresh-start, so this module never persists anything to disk.
export type E4Store = Map<string, Map<string, Record<string, unknown>>>;

export function createStore(seedFixture: Record<string, Record<string, unknown>[]>): E4Store {
  const store: E4Store = new Map();

  for (const [entityName, rows] of Object.entries(seedFixture)) {
    const table = new Map<string, Record<string, unknown>>();
    for (const row of rows) {
      table.set(String(row.id), row);
    }
    store.set(entityName, table);
  }

  return store;
}
`;

const SERVER_FILE_CONTENTS_V2 = `// Generic dispatcher, procedural-rest-v2 (E4V2 design §5.6.1). Behavior is entirely data-driven
// from registry.ts + schema.ts + seed.ts — this file never changes across substrate configs.
import { routeRegistry, type E4RouteDefinition } from "./registry";
import { entitySchemas, validationRules, errorEnvelopeStyle } from "./schema";
import { createStore } from "./storage";
import { seedFixture } from "./seed";

const store = createStore(seedFixture);
const port = Number(process.env.E4_PORT ?? "0");

function errorBody(code: string, message: string): unknown {
  return errorEnvelopeStyle === "type_detail" ? { error: { type: code, detail: message } } : { error: { code, message } };
}

function matchPath(pattern: string, pathname: string): Record<string, string> | null {
  const patternSegments = pattern.split("/").filter(Boolean);
  const actualSegments = pathname.split("/").filter(Boolean);

  if (patternSegments.length !== actualSegments.length) {
    return null;
  }

  const params: Record<string, string> = {};

  for (let i = 0; i < patternSegments.length; i += 1) {
    const patternSegment = patternSegments[i];
    const actualSegment = actualSegments[i];

    if (patternSegment.startsWith("{") && patternSegment.endsWith("}")) {
      params[patternSegment.slice(1, -1)] = actualSegment;
    } else if (patternSegment !== actualSegment) {
      return null;
    }
  }

  return params;
}

function literalSegmentCount(path: string): number {
  return path.split("/").filter((segment) => segment.length > 0 && !segment.startsWith("{")).length;
}

// More-specific (more literal-segment) routes must be tried before wildcard ones, or a route like
// GET /widgets/{id} (read) shadows GET /widgets/stats (analytics) — {id} matches "stats" too.
const routesBySpecificity = [...routeRegistry].sort((a, b) => literalSegmentCount(b.path) - literalSegmentCount(a.path));

function matchRoute(method: string, pathname: string): { route: E4RouteDefinition; params: Record<string, string> } | null {
  for (const route of routesBySpecificity) {
    if (route.method !== method) {
      continue;
    }
    const params = matchPath(route.path, pathname);
    if (params) {
      return { route, params };
    }
  }
  return null;
}

// §5.6.1 type checks: string/ref = JSON string, int = integer number, decimal = finite number
// (integers admissible), bool = boolean, date = string matching ^\\d{4}-\\d{2}-\\d{2}$.
function typeOk(fieldType: string, value: unknown): boolean {
  switch (fieldType) {
    case "string":
    case "ref":
      return typeof value === "string";
    case "int":
      return typeof value === "number" && Number.isInteger(value);
    case "decimal":
      return typeof value === "number" && Number.isFinite(value);
    case "bool":
      return typeof value === "boolean";
    case "date":
      return typeof value === "string" && /^\\d{4}-\\d{2}-\\d{2}$/.test(value);
    default:
      return false;
  }
}

function ruleOk(rule: { kind: string; detail: Record<string, unknown> }, value: unknown): boolean {
  if (rule.kind === "range") {
    if (typeof value !== "number") {
      return false;
    }
    const min = rule.detail.min;
    const max = rule.detail.max;
    return (typeof min !== "number" || value >= min) && (typeof max !== "number" || value <= max);
  }
  if (rule.kind === "enum") {
    const values = rule.detail.values;
    return Array.isArray(values) && values.includes(value);
  }
  if (rule.kind === "format") {
    return typeof value === "string" && typeof rule.detail.pattern === "string" && new RegExp(rule.detail.pattern).test(value);
  }
  return true;
}

// §5.6.1 sealed check order: unknown field → missing required → type → validation rule; the
// first failure wins. null is treated as absent (a required field set to null is missing; an
// optional field set to null is skipped by the type and rule checks).
function firstValidationFailure(entityName: string, body: Record<string, unknown>): string | null {
  const entity = entitySchemas.find((candidate) => candidate.name === entityName);
  const fields = entity?.fields ?? [];
  const knownFieldNames = new Set(fields.map((field) => field.name));

  for (const key of Object.keys(body)) {
    if (!knownFieldNames.has(key)) {
      return \`unknown field: \${key}\`;
    }
  }

  for (const field of fields) {
    if (field.required && (body[field.name] === undefined || body[field.name] === null)) {
      return \`\${field.name} is required\`;
    }
  }

  for (const field of fields) {
    const value = body[field.name];
    if (value === undefined || value === null) {
      continue;
    }
    if (!typeOk(field.type, value)) {
      return \`\${field.name} must be a \${field.type}\`;
    }
  }

  for (const rule of validationRules) {
    if (rule.entity !== entityName) {
      continue;
    }
    const value = body[rule.field];
    if (value === undefined || value === null) {
      continue;
    }
    if (!ruleOk(rule, value)) {
      return \`\${rule.field} is invalid\`;
    }
  }

  return null;
}

async function handle(req: Request): Promise<Response> {
  const url = new URL(req.url);
  const matched = matchRoute(req.method, url.pathname);

  if (!matched) {
    return Response.json(errorBody("not_found", "route not found"), { status: 404 });
  }

  const { route, params } = matched;
  const table = store.get(route.entity);

  if (!table) {
    return Response.json(errorBody("not_found", "unknown entity"), { status: 404 });
  }

  switch (route.kind) {
    case "create": {
      const body = (await req.json()) as Record<string, unknown>;
      const failure = firstValidationFailure(route.entity, body);
      if (failure) {
        return Response.json(errorBody("validation_error", failure), { status: 400 });
      }
      table.set(String(body.id), body);
      return Response.json(body, { status: 201 });
    }
    case "read": {
      const row = table.get(params.id);
      if (!row) {
        return Response.json(errorBody("not_found", "resource not found"), { status: 404 });
      }
      return Response.json(row, { status: 200 });
    }
    case "update": {
      if (!table.has(params.id)) {
        return Response.json(errorBody("not_found", "resource not found"), { status: 404 });
      }
      const body = (await req.json()) as Record<string, unknown>;
      const failure = firstValidationFailure(route.entity, body);
      if (failure) {
        return Response.json(errorBody("validation_error", failure), { status: 400 });
      }
      table.set(params.id, body);
      return Response.json(body, { status: 200 });
    }
    case "delete": {
      if (!table.has(params.id)) {
        return Response.json(errorBody("not_found", "resource not found"), { status: 404 });
      }
      table.delete(params.id);
      return new Response(null, { status: 204 });
    }
    case "list": {
      const refField = entitySchemas.find((entity) => entity.name === route.entity)?.fields.find((field) => field.type === "ref");
      const filterValue = refField ? url.searchParams.get(refField.name) : null;
      const rows = [...table.values()].filter((row) => !filterValue || row[refField!.name] === filterValue);
      return Response.json(rows, { status: 200 });
    }
    case "analytics": {
      return Response.json({ count: table.size }, { status: 200 });
    }
    default: {
      return Response.json(errorBody("not_found", "unknown route kind"), { status: 404 });
    }
  }
}

const server = Bun.serve({ port, fetch: handle });
console.log(\`E4 app listening on port \${server.port}\`);
`;

// The runnable app files only — the v2-M1 workspace generator layers the OpenSpec tree and the
// re-authored README on top of these.
export function buildE4V2AppFiles(ir: E4SchemaIR): Record<string, string> {
  return {
    "server.ts": SERVER_FILE_CONTENTS_V2,
    "storage.ts": STORAGE_FILE_CONTENTS,
    "registry.ts": registryFileContents(ir),
    "schema.ts": schemaFileContents(ir),
    "seed.ts": seedFileContents(ir)
  };
}
