// E4 v3-M2 (E4V3-PRODUCT-LOOP-PROPOSAL.md §3.1): mutation testing on the AGENT'S OWN
// implementation — the product arm's anti-cheat gate component. Needs no hidden truth: the
// question it answers is "would this scenario suite notice if the agent's API misbehaved in
// way X?".
//
// Mechanism: boundary mutants. A mutant workspace is a copy of the agent workspace whose
// `server.ts` entrypoint is replaced by a generated, self-contained proxy that (a) spawns the
// agent's real server (renamed alongside it), (b) satisfies the sealed stdout-port handshake the
// pinned scenario executor expects, and (c) applies ONE sealed behavioral mutation at the HTTP
// boundary. This is code-shape independent (agents may restructure everything except the sealed
// `server.ts` + port-handshake contract, which the gate's smoke already requires) and leaves the
// pinned executor byte-untouched — it talks to the proxy unknowingly.
//
// Role note (adjudication): the v2 anti-cheat adjudication rejected mutation tooling as a hidden
// MEASUREMENT instrument. This harness is ARM FEEDBACK inside the product gate — a different
// role. The hidden bank + oracle remain the untouched measurement; this module never reads
// ground truth.
//
// Kill discipline (M5 instrument insight, agent-side analog): only scenarios GREEN on the
// agent's real server earn kill credit — a scenario failing on the real code would "kill" every
// mutant spuriously. Non-completed verdicts (readiness/executor errors) never count as kills;
// a mutant with no killer and any non-completed verdict is `unevaluable` and scores as
// not-killed (fail-closed toward gate feedback).
import { cpSync, existsSync, mkdirSync, renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { E4V2Scenario } from "../v2/scenario";
import { E4_V2_EXECUTOR_ENTRYPOINT, runE4V2ScenarioSet, type E4V2ScenarioVerdict } from "../v2/scenario-executor";

export const E4_V3_MUTATION_HARNESS_ID = "e4-agent-boundary-mutation-v1";
export const E4_V3_REAL_SERVER_ENTRY = "__e4_v3_real_server.ts";

export const E4_V3_MUTANT_IDS = [
  "accept-invalid", // 400 on a write becomes a fabricated success (validation-dropped analog)
  "status-swap", // 201 -> 200; 404 -> 200 {} (status-swapped analog)
  "swallow-write", // PUT/PATCH/DELETE never reach the server; fabricated success (no-op-write analog)
  "field-leak", // 2xx JSON responses gain an undocumented field (field-leak analog)
  "strip-filter", // GET query strings are dropped before forwarding (wrong-filter analog)
  "empty-list" // 2xx JSON array responses become [] (seed-echo/list-integrity analog)
] as const;

export type E4V3MutantId = (typeof E4_V3_MUTANT_IDS)[number];

export type E4V3MutantVerdict = {
  mutant_id: E4V3MutantId;
  status: "killed" | "survived" | "unevaluable";
  killing_scenario_titles: string[];
  non_completed_titles: string[];
};

export type E4V3MutationReport = {
  harness_id: typeof E4_V3_MUTATION_HARNESS_ID;
  baseline_green_titles: string[];
  baseline_failed_titles: string[]; // no kill credit; surfaced as their own gate feedback
  baseline_non_completed_titles: string[];
  mutants: E4V3MutantVerdict[];
  kill_score: number | null; // killed / mutants; null when no green baseline scenario exists
};

// The generated proxy entrypoint. Self-contained Bun code — no imports, so it survives any
// agent restructuring of the rest of the workspace.
function proxySource(mutantId: E4V3MutantId): string {
  return `// E4 v3 boundary-mutant proxy — generated by ${E4_V3_MUTATION_HARNESS_ID}; not agent code.
const MUTANT_ID = ${JSON.stringify(mutantId)};

const child = Bun.spawn(["bun", ${JSON.stringify(E4_V3_REAL_SERVER_ENTRY)}], {
  cwd: import.meta.dir,
  env: { ...process.env, E4_PORT: "0" },
  stdout: "pipe",
  stderr: "inherit"
});

function killChild() {
  try {
    child.kill();
  } catch {}
}
process.on("SIGTERM", () => { killChild(); process.exit(0); });
process.on("SIGINT", () => { killChild(); process.exit(0); });
process.on("exit", killChild);

const reader = child.stdout.getReader();
const decoder = new TextDecoder();
let buffer = "";
let upstreamPort = 0;

while (upstreamPort === 0) {
  const chunk = await reader.read();
  if (chunk.done) break;
  buffer += decoder.decode(chunk.value, { stream: true });
  const match = buffer.match(/listening on port (\\d+)/);
  if (match) upstreamPort = Number(match[1]);
}

if (upstreamPort === 0) {
  console.error("mutant proxy: real server never became ready");
  killChild();
  process.exit(1);
}

// keep draining the child's stdout so it can never block on a full pipe
(async () => {
  try {
    while (true) {
      const chunk = await reader.read();
      if (chunk.done) break;
    }
  } catch {}
})();

const upstream = "http://127.0.0.1:" + upstreamPort;

function json(status, value) {
  return new Response(JSON.stringify(value), { status, headers: { "content-type": "application/json" } });
}

function parseOr(text, fallback) {
  if (text === null || text.length === 0) return fallback;
  try {
    const parsed = JSON.parse(text);
    return parsed !== null && typeof parsed === "object" ? parsed : fallback;
  } catch {
    return fallback;
  }
}

const server = Bun.serve({
  port: Number(process.env.E4_PORT ?? "0"),
  async fetch(req) {
    const url = new URL(req.url);
    let pathAndQuery = url.pathname + url.search;
    const method = req.method;
    const bodyText = method === "GET" || method === "DELETE" || method === "HEAD" ? null : await req.text();

    if (MUTANT_ID === "strip-filter" && method === "GET") {
      pathAndQuery = url.pathname;
    }

    if (MUTANT_ID === "swallow-write" && (method === "PUT" || method === "PATCH" || method === "DELETE")) {
      return method === "DELETE" ? json(200, {}) : json(200, parseOr(bodyText, {}));
    }

    const response = await fetch(upstream + pathAndQuery, {
      method,
      headers: bodyText !== null ? { "content-type": "application/json" } : {},
      ...(bodyText !== null ? { body: bodyText } : {})
    });
    const responseText = await response.text();
    let status = response.status;
    let parsed;
    let isJson = false;

    if (responseText.length > 0) {
      try {
        parsed = JSON.parse(responseText);
        isJson = true;
      } catch {
        isJson = false;
      }
    }

    if (MUTANT_ID === "accept-invalid" && status === 400 && (method === "POST" || method === "PUT" || method === "PATCH")) {
      return json(method === "POST" ? 201 : 200, parseOr(bodyText, {}));
    }

    if (MUTANT_ID === "status-swap") {
      if (status === 201) status = 200;
      else if (status === 404) return json(200, {});
    }

    if (MUTANT_ID === "field-leak" && isJson && status >= 200 && status < 300) {
      if (parsed !== null && typeof parsed === "object" && !Array.isArray(parsed)) {
        parsed.__debug = "leak";
      } else if (Array.isArray(parsed)) {
        for (const item of parsed) {
          if (item !== null && typeof item === "object") item.__debug = "leak";
        }
      }
      return json(status, parsed);
    }

    if (MUTANT_ID === "empty-list" && method === "GET" && isJson && Array.isArray(parsed) && status < 300) {
      return json(status, []);
    }

    return new Response(responseText, {
      status,
      headers: isJson ? { "content-type": "application/json" } : {}
    });
  }
});

console.log("E4 mutation proxy (" + MUTANT_ID + ") listening on port " + server.port);
`;
}

export function prepareE4MutantWorkspace(input: {
  workspaceDir: string;
  mutantId: E4V3MutantId;
  scratchRoot: string;
}): string {
  const mutantDir = join(input.scratchRoot, `mutant-${input.mutantId}`);

  mkdirSync(mutantDir, { recursive: true });
  cpSync(input.workspaceDir, mutantDir, { recursive: true });

  const realEntry = join(mutantDir, E4_V3_REAL_SERVER_ENTRY);

  if (existsSync(realEntry)) {
    throw new Error(`workspace already carries the reserved entry name ${E4_V3_REAL_SERVER_ENTRY}`);
  }

  renameSync(join(mutantDir, E4_V2_EXECUTOR_ENTRYPOINT), realEntry);
  writeFileSync(join(mutantDir, E4_V2_EXECUTOR_ENTRYPOINT), proxySource(input.mutantId));

  return mutantDir;
}

type ExecutorConfig = Parameters<typeof runE4V2ScenarioSet>[0]["config"];

function completedFailures(verdicts: E4V2ScenarioVerdict[]): string[] {
  return verdicts
    .filter((verdict) => verdict.kind === "completed" && !verdict.passed)
    .map((verdict) => verdict.title);
}

function nonCompleted(verdicts: E4V2ScenarioVerdict[]): string[] {
  return verdicts.filter((verdict) => verdict.kind !== "completed").map((verdict) => verdict.title);
}

export async function runE4AgentMutationAnalysis(input: {
  workspaceDir: string;
  scenarios: E4V2Scenario[];
  config: ExecutorConfig;
  scratchRoot: string;
  concurrency?: number;
}): Promise<E4V3MutationReport> {
  const baseline = await runE4V2ScenarioSet({
    workspace_dir: input.workspaceDir,
    scenarios: input.scenarios,
    config: input.config,
    concurrency: input.concurrency
  });

  const greenTitles = new Set(
    baseline.filter((verdict) => verdict.kind === "completed" && verdict.passed).map((verdict) => verdict.title)
  );
  const greenScenarios = input.scenarios.filter((scenario) => greenTitles.has(scenario.title));

  const report: E4V3MutationReport = {
    harness_id: E4_V3_MUTATION_HARNESS_ID,
    baseline_green_titles: [...greenTitles],
    baseline_failed_titles: completedFailures(baseline),
    baseline_non_completed_titles: nonCompleted(baseline),
    mutants: [],
    kill_score: null
  };

  if (greenScenarios.length === 0) {
    return report; // nothing can earn kill credit; the gate treats this as failing feedback
  }

  for (const mutantId of E4_V3_MUTANT_IDS) {
    const mutantDir = prepareE4MutantWorkspace({
      workspaceDir: input.workspaceDir,
      mutantId,
      scratchRoot: input.scratchRoot
    });
    const verdicts = await runE4V2ScenarioSet({
      workspace_dir: mutantDir,
      scenarios: greenScenarios,
      config: input.config,
      concurrency: input.concurrency
    });
    const killers = completedFailures(verdicts);
    const infra = nonCompleted(verdicts);

    report.mutants.push({
      mutant_id: mutantId,
      status: killers.length > 0 ? "killed" : infra.length > 0 ? "unevaluable" : "survived",
      killing_scenario_titles: killers,
      non_completed_titles: infra
    });
  }

  report.kill_score =
    report.mutants.filter((mutant) => mutant.status === "killed").length / report.mutants.length;

  return report;
}
